# Site settings
title: UDW23
email: udw-organisers@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Universal Dependencies Workshop 2023 (UDW'23)
baseurl: "/udw23" # the subpath of your site, e.g. /blog/
url: "http://universaldependencies.org" # the base hostname & protocol for your site
twitter_username: ud_workshop
# github_username:  jekyll

# Build settings
markdown: kramdown
