# Site settings
title: UDW25
email: udw-organisers@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Universal Dependencies Workshop 2025 (UDW'25)
baseurl: "/udw25" # the subpath of your site, e.g. /blog/
url: "http://universaldependencies.org" # the base hostname & protocol for your site
twitter_username: ud_workshop
# github_username:  jekyll

# Build settings
markdown: kramdown
